import Providers from "@/core/components/providers/providers";
import type { Metadata, Viewport } from "next";
import "./globals.css";
import cn from "@/core/utils/cn";
import { notoSans, notoSansMono, notoSansThai } from "@/core/configs/fonts";
import { AntdRegistry } from "@ant-design/nextjs-registry";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export const viewport: Viewport = {
  minimumScale: 1
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(notoSansThai.variable, notoSans.variable, notoSansMono.variable, "antialiased")}
    >
      <body>
        <AntdRegistry>
          <Providers>{children}</Providers>
        </AntdRegistry>
      </body>
    </html>
  );
}
